# Generated by Django 3.2.9 on 2021-12-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0002_rename_object_object5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object5',
        ),
    ]
