# Generated by Django 3.2.9 on 2021-12-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0003_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
    ]
