# Generated by Django 3.2.9 on 2021-12-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ispy', '0003_delete_object5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_url', models.TextField(max_length=2000)),
                ('object_name', models.CharField(max_length=255)),
                ('object_confidence_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('object_notes', models.TextField(max_length=1000)),
            ],
        ),
    ]
