# Generated by Django 3.2.9 on 2021-12-15 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0004_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='search_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='ispy.searchtype'),
            preserve_default=False,
        ),
    ]
