# Generated by Django 3.2.9 on 2021-12-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0005_auto_20211215_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='search_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object1', to='ispy.searchtype'),
        ),
    ]
