# Generated by Django 3.2.9 on 2021-12-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0006_alter_object_search_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='search_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_object', to='ispy.searchtype'),
        ),
    ]
