# Generated by Django 3.2.9 on 2021-12-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0007_alter_object_search_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='search_type',
        ),
        migrations.DeleteModel(
            name='SearchType',
        ),
    ]
