# Generated by Django 3.2.9 on 2021-12-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0009_auto_20211215_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_url', models.TextField(max_length=2000)),
                ('face_name', models.CharField(max_length=255)),
                ('face_gender', models.CharField(max_length=255)),
                ('face_age', models.IntegerField()),
                ('face_hair_color1', models.CharField(max_length=255)),
                ('face_hair_color2', models.CharField(max_length=255)),
                ('face_anger', models.DecimalField(decimal_places=2, max_digits=5)),
                ('face_contempt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('face_disgust', models.DecimalField(decimal_places=2, max_digits=5)),
                ('face_fear', models.DecimalField(decimal_places=2, max_digits=5)),
                ('face_happiness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('face_neutral', models.DecimalField(decimal_places=2, max_digits=5)),
                ('face_sadness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('face_suprise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('object_notes', models.TextField(max_length=1000)),
                ('search_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_face', to='ispy.searchtype')),
            ],
        ),
    ]
