# Generated by Django 3.2.9 on 2021-12-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0010_face'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='object_notes',
            new_name='face_notes',
        ),
    ]
