# Generated by Django 3.2.9 on 2021-12-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0011_rename_object_notes_face_face_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchType',
            new_name='Scan',
        ),
        migrations.RenameField(
            model_name='scan',
            old_name='search_name',
            new_name='scan_name',
        ),
        migrations.RemoveField(
            model_name='face',
            name='search_type',
        ),
        migrations.RemoveField(
            model_name='object',
            name='search_type',
        ),
        migrations.AddField(
            model_name='face',
            name='scan_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scan_face', to='ispy.scan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='scan_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scan_object', to='ispy.scan'),
            preserve_default=False,
        ),
    ]
