# Generated by Django 3.2.9 on 2021-12-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ispy', '0013_rename_face_suprise_face_face_surprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_url', models.TextField(max_length=2000)),
                ('adult_name', models.CharField(max_length=255)),
                ('adult_adult_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adult_racy_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adult_gore_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adult_notes', models.TextField(max_length=1000)),
                ('scan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_adult', to='ispy.scan')),
            ],
        ),
    ]
